            <footer>
                <div class="row justify-content-center">
                    <span>Copyright &copy; Family Weight Tracker- <?php echo date("Y");?> </span>
                </div>

            </footer>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
            <script src="format_confirmation/newAccountForm.js"></script>
            <script src="format_confirmation/validateLogin.js"></script>
            <script src="/resources/history_log/historyLog.js"></script>
            <script src="/resources/rankings/rankingList.js"></script>
            <script src="/resources/rankings/selfRank.js"></script>
            <script src="/resources/calculations/bmi.js"></script>
    </body>
</html>