<DOCTYPE html>
    <html lang="en">
    <head>
        <meta name="viewport" content="width=devices-width, initial-scale=1">
        <meta charset="utf-8">
        <meta name="description" content="family weight loss tracker competition">
        <title><?php echo $page_title; ?></title>
        <link rel="stylesheet" href="/public/components.css" type="text/css">
        <link rel="stylesheet" href="/public/login.css" type="text/css">
        <link rel="stylesheet" href="/public/spacing.css" type="text/css">
    
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
 
 
    </head>