<DOCTYPE html>
    <html lang="en">
    <head>
        <meta name="viewport" content="width=devices-width, initial-scale=1">
        <meta charset="utf-8">
        <meta name="description" content="family weight loss tracker competition">
        <title><?php echo $page_title; ?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="/public/components.css" type="text/css">
    </head>