  
    <ul class="navbar nav fixed-top nav-justified" style="background-color: #235f99;">

        <li class="nav-item">
            <a style="color: #FFFFFF;" class="nav-link" href="/index.php">Home<span class="sr-only">(current)</span></a>
        </li>


        <li class="nav-item">
            <a style="color: #FFFFFF;" class="nav-link" href="/stats.php">Stats<span class="sr-only">(current)</span></a>
        </li>


        <li class="nav-item">
            <a style="color: #FFFFFF;" class="nav-link" href="/tips.php">Tips<span class="sr-only">(current)</span></a>
        </li>


        <li class="nav-item">
            <a style="color: #FFFFFF;" class="nav-link" href="accountsettings.php">Account<span class="sr-only">(current)</span></a>
        </li>

    </ul>
<!-- END NAVBAR -->